/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;

/**
 *
 * @author danielsanchez
 */
public class AtaquePanel extends javax.swing.JPanel {

    /**
     * Creates new form AtaquePanel
     */
    public AtaquePanel() {
        initComponents();
        this.setPreferredSize(new Dimension(100, 100));
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Llama primaria (base del ataque)
        g2d.setColor(new Color(255, 100, 0, 180)); // Naranja, semi-transparente
        g2d.fillOval(20, 20, 60, 60);

        // Llama secundaria (parte más brillante)
        g2d.setColor(new Color(255, 150, 0, 200)); // Naranja más claro, semi-transparente
        g2d.fillOval(25, 25, 50, 50);

        // Llama central (parte amarilla)
        g2d.setColor(new Color(255, 200, 0, 220)); // Amarillo, semi-transparente
        g2d.fillOval(30, 30, 40, 40);

        // Puntas de las llamas (pequeñas llamaradas alrededor)
        g2d.setColor(new Color(255, 80, 0, 150));
        g2d.fillOval(35, 10, 15, 25);
        g2d.fillOval(50, 5, 20, 30);
        g2d.fillOval(65, 10, 15, 25);

        // Añade líneas adicionales para simular movimiento
        g2d.setColor(new Color(255, 50, 0, 180));
        g2d.drawLine(50, 50, 60, 15);
        g2d.drawLine(60, 50, 70, 15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        // Crea el marco de la aplicación
        JFrame frame = new JFrame("Ataque Pokémon - Lanzallamas");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Añade el panel de ataque Pokémon al marco
        AtaquePanel attackPanel = new AtaquePanel();
        frame.add(attackPanel);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}
